---
service: tannisNotificationServicesLambda
frameworkVersion: '2'
provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: ap-south-1
  timeout: 30
  logRetentionInDays: 1
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 1
  iam:
    role: arn:aws:iam::502860870433:role/service-role/test-role-elybze7y
  vpc:
    securityGroupIds:
      - sg-0749bdf075ecccb19
    subnetIds:
      - subnet-0e14a634124b0f965
      - subnet-08b504261a6d7b39b
package:
  patterns:
    - '!.git/**'
    - '!.serverless/**'
    - '!.gitignore'
    - '!LICENSE'
    - '!README.md'
    - '!serverless.yml'
    - '!package-lock.json'
    - '!tsconfig.json'

functions:
  mailing:
    handler: mailProcessor.handler
    description: Send notification mails on behalf of tannis chat app.

plugins:
  - serverless-plugin-typescript
